jupyterlab:
  image: ${IMAGE_TAG}
  ports:
    - "8888:8888"
  volumes:
    - ../notebooks:/home/jovyan/notebooks/
    - $HOME/.aws/:/home/jovyan/.aws/
  environment:
    - JUPYTER_ENABLE_LAB=yes
    - GRANT_SUDO=yes
  user: root
  stdin_open: true
  entrypoint: jupyter lab --ip='0.0.0.0' --notebook-dir=/home/jovyan/notebooks --config=/home/jovyan/.jupyter/jupyter_notebook_config.py --allow-root
