jupyterlab:
  image: ${IMAGE_TAG}
  ports:
    - "8888:8888"
  volumes:
    - ./notebooks:/home/jovyan/notebooks/
    - $HOME/.aws/:/home/jovyan/.aws/
  environment:
    - JUPYTER_ENABLE_LAB=yes
    - GRANT_SUDO=yes
  user: root
  entrypoint: papermill /home/jovyan/repo/${SCRIPT_PATH} s3://job-outputs/output.ipynb