AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates:
  - CFNUserGroup and CFNAdminGroup IAM groups. Note that 
  CFNAdminGroup has full admin powers! 
  - CFNUser IAM user associated with both of these groups
  - a policy, role and associated instance profile which allow an 
  EC2 instances to access S3 buckets.
  - a new ElasticIp (EIP).
  Note that you will need to specify the CAPABILITY_IAM flag when you 
  create the stack to allow this template to execute.
Parameters:
  RepositoryName:
    Description: Name of the codecommit repo for this project
    Default: data-science-stack
    Type: String
  S3BucketName:
    Description: Name of the S3 bucket which will hold job outputs
    Default: data-science-stack-outputs
    Type: String
Resources:
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: Repo to allow EC2 access to the DataScienceStack environment.
      RepositoryName: data-science-stack
  InstanceECR:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref RepositoryName
  ListS3BucketsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ListS3BucketsRole
  ListS3BucketsPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: ListS3BucketsPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
              - 'codecommit:*'
              - 'ecr:*'
            Resource: '*'
      Roles:
        - !Ref ListS3BucketsRole
  ListS3BucketsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref S3BucketName
    DeletionPolicy: Delete
Outputs:
  InstanceRole:
    Value: !Ref ListS3BucketsInstanceProfile
    Export:
      Name: "InstanceProfile::S3Access"
  S3BucketName:
    Value: !Ref S3BucketName
    Export:
      Name: "S3Bucketname"
  CodeCommitAddress:
    Value: !GetAtt CodeCommitRepo.CloneUrlHttp
    Export:
      Name: "CodeCommitAddress"
